In [10]:
import numpy as np
import pandas as pd

In [11]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D', 'E'] * 4,
    'Region': ['East', 'West', 'North', 'South', 'East'] * 4,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John'] * 4
}
df = pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Q']=df['Date'].dt.quarter.astype(str)

In [12]:
df

         Date Product Region  Sales  Units    Rep    Month  Q
0  2023-01-01       A   East    467     27   John  January  1
1  2023-01-02       B   West    821     45   Mary  January  1
2  2023-01-03       C  North    803     26    Bob  January  1
3  2023-01-04       D  South    784     55  Alice  January  1
4  2023-01-05       E   East    400     58   John  January  1
5  2023-01-06       A   East    690     98   John  January  1
6  2023-01-07       B   West    129     92   Mary  January  1
7  2023-01-08       C  North    455     27    Bob  January  1
8  2023-01-09       D  South    993     49  Alice  January  1
9  2023-01-10       E   East    957     46   John  January  1
10 2023-01-11       A   East    343     36   John  January  1
11 2023-01-12       B   West    478     63   Mary  January  1
12 2023-01-13       C  North    737     81    Bob  January  1
13 2023-01-14       D  South    848     15  Alice  January  1
14 2023-01-15       E   East    814     11   John  January  1
15 2023-01-16       A   East    408     14   John  January  1
16 2023-01-17       B   West    606     62   Mary  January  1
17 2023-01-18       C  North    392     89    Bob  January  1
18 2023-01-19       D  South    698     46  Alice  January  1
19 2023-01-20       E   East    642     94   John  January  1

In [13]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product")

Product      A      B       C       D       E
Region
East     477.0    NaN     NaN     NaN  703.25
North      NaN    NaN  596.75     NaN     NaN
South      NaN    NaN     NaN  830.75     NaN
West       NaN  508.5     NaN     NaN     NaN

In [14]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc='median')

Product      A      B      C      D      E
Region
East     437.5    NaN    NaN    NaN  728.0
North      NaN    NaN  596.0    NaN    NaN
South      NaN    NaN    NaN  816.0    NaN
West       NaN  542.0    NaN    NaN    NaN

In [17]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                                 Units                      \
Product      A      B       C       D       E      A     B      C      D
Region
East     477.0    NaN     NaN     NaN  703.25  43.75   NaN    NaN    NaN
North      NaN    NaN  596.75     NaN     NaN    NaN   NaN  55.75    NaN
South      NaN    NaN     NaN  830.75     NaN    NaN   NaN    NaN  41.25
West       NaN  508.5     NaN     NaN     NaN    NaN  65.5    NaN    NaN


Product      E
Region
East     52.25
North      NaN
South      NaN
West       NaN

Cross Tabs

In [20]:
pd.crosstab(df["Region"],df['Product'])

Product  A  B  C  D  E
Region
East     4  0  0  0  4
North    0  0  4  0  0
South    0  0  0  4  0
West     0  4  0  0  0